GET http://localhost:5173/api/users
###
POST http://localhost:5173/api/users
Content-Type: application/json

{
    "isAuthenticated": true,
    "userIdWithGithub": "github|118256347",
    "userIdWithGoogle": "",
    "userName": "Aoi Tanaka"
}

###
PUT http://localhost:5173/api/user/Aoi%20Tanaka
Content-Type: application/json

[
  {
    "link": "https://www.healthyeating.org/images/default-source/home-0.0/nutrition-topics-2.0/general-nutrition-wellness/2-2-2-3foodgroups_fruits_detailfeature.jpg?sfvrsn=64942d53_4",      
    "title": "Fruits"
  },
  {
    "link": "https://cdn-prod.medicalnewstoday.com/content/images/articles/325/325253/assortment-of-fruits.jpg",
    "title":" Is there a best time to eat fruit? Facts and myths"
  }
]

